# Generated by Django 4.2.1 on 2023-05-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=10)),
                ('level', models.IntegerField()),
                ('department', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=3)),
                ('birthdate', models.DateField()),
            ],
        ),
    ]
